import 'dart:ui';

import 'package:chinese_learning_app/global_variables/global_colors.dart';

class DummyDataFriends {
  static final cardData = [
    {
      'word': 'Lǎo tiě',
      'chinese': '老铁',
      'soundAsset': 'assets/sound_clips/friends/1.m4a',
      'meaning': 'buddy (bro)',
      'image': 'assets/images/friends/1.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Zuìjìn zěnme yàng a',
      'chinese': '最近怎么样啊',
      'soundAsset': 'assets/sound_clips/friends/2.m4a',
      'meaning': 'How’ve you been lately?',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Tǐng lèi de',
      'chinese': '挺累的',
      'soundAsset': 'assets/sound_clips/friends/3.m4a',
      'meaning': 'quite tired',
      'image': 'assets/images/friends/3.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Máng dé yàomìng',
      'chinese': '忙得要命',
      'soundAsset': 'assets/sound_clips/friends/4.m4a',
      'meaning':
          'extremely busy (want to express that so busy that one can lose his or her life)',
      'image': 'assets/images/friends/4.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Bié tài pīnle',
      'chinese': '别太拼了',
      'soundAsset': 'assets/sound_clips/friends/5.m4a',
      'meaning': 'don’t put effort too much',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Zhùyì shēntǐ',
      'chinese': '注意身体',
      'soundAsset': 'assets/sound_clips/friends/6.m4a',
      'meaning': 'take care of your health',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Jǐnliàng',
      'chinese': '尽量',
      'soundAsset': 'assets/sound_clips/friends/7.m4a',
      'meaning': 'will try my best',
      'image': 'assets/images/friends/7.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Xīnxiān shìwù',
      'chinese': '新鲜事儿',
      'soundAsset': 'assets/sound_clips/friends/8.m4a',
      'meaning': 'recent updates',
      'image': 'assets/images/friends/8.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Wán yóuxì',
      'chinese': '玩游戏',
      'soundAsset': 'assets/sound_clips/friends/9.m4a',
      'meaning': 'play games',
      'image': 'assets/images/friends/9.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Bù yì lè hū',
      'chinese': '不亦乐乎',
      'soundAsset': 'assets/sound_clips/friends/10.m4a',
      'meaning': 'Very happy',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Xiǎoxīn',
      'chinese': '小心',
      'soundAsset': 'assets/sound_clips/friends/11.m4a',
      'meaning': 'be careful',
      'image': 'assets/images/friends/11.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Chénmí',
      'chinese': '沉迷',
      'soundAsset': 'assets/sound_clips/friends/12.m4a',
      'meaning': 'get addicted to',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Chéng',
      'chinese': '成',
      'soundAsset': 'assets/sound_clips/friends/13.m4a',
      'meaning': 'become',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Diàn jìng gǒu',
      'chinese': '电竞狗',
      'soundAsset': 'assets/sound_clips/friends/14.m4a',
      'meaning': 'gaming addict',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Fàngxīn',
      'chinese': '放心',
      'soundAsset': 'assets/sound_clips/friends/15.m4a',
      'meaning': 'don’t worry',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Bǎwò',
      'chinese': '把握',
      'soundAsset': 'assets/sound_clips/friends/16.m4a',
      'meaning': 'grasp',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Hǎo dù',
      'chinese': '好度',
      'soundAsset': 'assets/sound_clips/friends/17.m4a',
      'meaning': 'to a good level',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Bǎwò hǎo dù',
      'chinese': '把握好度',
      'soundAsset': 'assets/sound_clips/friends/18.m4a',
      'meaning': 'control well',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Diànyǐng',
      'chinese': '电影',
      'soundAsset': 'assets/sound_clips/friends/19.m4a',
      'meaning': 'movie',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Shàngyìng',
      'chinese': '上映',
      'soundAsset': 'assets/sound_clips/friends/20.m4a',
      'meaning': 'release',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Chǎngmiàn',
      'chinese': '场面',
      'soundAsset': 'assets/sound_clips/friends/21.m4a',
      'meaning': 'scenes',
      'image': 'assets/images/friends/21.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Zhènhàn',
      'chinese': '震撼',
      'soundAsset': 'assets/sound_clips/friends/22.m4a',
      'meaning': 'thrilling',
      'image': 'assets/images/friends/22.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Dǎoyǎn',
      'chinese': '导演',
      'soundAsset': 'assets/sound_clips/friends/23.m4a',
      'meaning': 'director',
      'image': 'assets/images/friends/23.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Dàliàng shíjiān',
      'chinese': '大量时间',
      'soundAsset': 'assets/sound_clips/friends/24.m4a',
      'meaning': 'a lot of time',
      'image': 'assets/images/friends/24.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Jīnglì',
      'chinese': '精力',
      'soundAsset': 'assets/sound_clips/friends/25.m4a',
      'meaning': 'effort',
      'image': 'assets/images/friends/25.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Xiàoguǒ',
      'chinese': '效果',
      'soundAsset': 'assets/sound_clips/friends/26.m4a',
      'meaning': 'result',
      'image': 'assets/images/friends/26.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Chūsè',
      'chinese': '出色',
      'soundAsset': 'assets/sound_clips/friends/27.m4a',
      'meaning': 'outstanding, remarkable',
      'image': 'assets/images/friends/27.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Nǐ yǒu kòng dehu',
      'chinese': '你有空的话',
      'soundAsset': 'assets/sound_clips/friends/28.m4a',
      'meaning': 'if you are free',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Zhōumò',
      'chinese': '周末',
      'soundAsset': 'assets/sound_clips/friends/29.m4a',
      'meaning': 'weekend',
      'image': 'assets/images/friends/29.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Jìhuà',
      'chinese': '计划',
      'soundAsset': 'assets/sound_clips/friends/30.m4a',
      'meaning': 'plan',
      'image': 'assets/images/friends/30.png',
      'color': GlobalColors.purple,
      'read': false,
    },
  ];
}
