import 'dart:ui';

import 'package:chinese_learning_app/global_variables/global_colors.dart';

final cardData = [
  {
    'word': '(Nǐ hǎo)',
    'chinese': '你好',
    'soundAsset': 'assets/sound_clips/1.mp3',
    'meaning': 'Hello!',
    'image': 'assets/images/hello.jpeg',
    'color': const Color.fromARGB(255, 96, 168, 202),
    'read': false,
  },
  {
    'word': '(Bàoqiàn)',
    'chinese': '抱歉',
    'soundAsset': 'assets/sound_clips/3.mp3',
    'meaning': 'Sorry',
    'image': 'assets/images/sorry.jpeg',
    'color': GlobalColors.purple,
    'read': false,
  },
  {
    'word': '(Xièxiè)',
    'chinese': '谢谢',
    'soundAsset': 'assets/sound_clips/2.mp3',
    'meaning': 'Thank You!',
    'image': 'assets/images/thankyou.jpg',
    'color': GlobalColors.secondary,
    'read': false,
  },
  {
    'word': '(Zàijiàn)',
    'chinese': '再见',
    'soundAsset': 'assets/sound_clips/4.mp3',
    'meaning': 'Goodbye',
    'image': 'assets/images/bye.jpg',
    'color': GlobalColors.primary,
    'read': false,
  },
  {
    'word': '(Nǐ hǎo)',
    'chinese': '你好',
    'soundAsset': 'assets/sound_clips/1.mp3',
    'meaning': 'Hello!',
    'image': 'assets/images/hello.jpeg',
    'color': const Color.fromARGB(255, 96, 168, 202),
    'read': false,
  },
  {
    'word': '(Bàoqiàn)',
    'chinese': '抱歉',
    'soundAsset': 'assets/sound_clips/3.mp3',
    'meaning': 'Sorry',
    'image': 'assets/images/sorry.jpeg',
    'color': GlobalColors.purple,
    'read': false,
  },
  {
    'word': '(Xièxiè)',
    'chinese': '谢谢',
    'soundAsset': 'assets/sound_clips/2.mp3',
    'meaning': 'Thank You!',
    'image': 'assets/images/thankyou.jpg',
    'color': GlobalColors.secondary,
    'read': false,
  },
  {
    'word': '(Zàijiàn)',
    'chinese': '再见',
    'soundAsset': 'assets/sound_clips/4.mp3',
    'meaning': 'Goodbye',
    'image': 'assets/images/bye.jpg',
    'color': GlobalColors.primary,
    'read': false,
  },
  {
    'word': '(Nǐ hǎo)',
    'chinese': '你好',
    'soundAsset': 'assets/sound_clips/1.mp3',
    'meaning': 'Hello!',
    'image': 'assets/images/hello.jpeg',
    'color': const Color.fromARGB(255, 96, 168, 202),
    'read': false,
  },
  {
    'word': '(Bàoqiàn)',
    'chinese': '抱歉',
    'soundAsset': 'assets/sound_clips/3.mp3',
    'meaning': 'Sorry',
    'image': 'assets/images/sorry.jpeg',
    'color': GlobalColors.purple,
    'read': false,
  },
  {
    'word': '(Xièxiè)',
    'chinese': '谢谢',
    'soundAsset': 'assets/sound_clips/2.mp3',
    'meaning': 'Thank You!',
    'image': 'assets/images/thankyou.jpg',
    'color': GlobalColors.secondary,
    'read': false,
  },
  {
    'word': '(Zàijiàn)',
    'chinese': '再见',
    'soundAsset': 'assets/sound_clips/4.mp3',
    'meaning': 'Goodbye',
    'image': 'assets/images/bye.jpg',
    'color': GlobalColors.primary,
    'read': false,
  }
];
