import 'dart:ui';

import 'package:chinese_learning_app/global_variables/global_colors.dart';

class DummyData {
  static final cardData = [
    {
      'word': '(Tóngxué)',
      'chinese': '同学 ',
      'soundAsset': 'assets/sound_clips/classroom/1.m4a',
      'meaning': 'Classmates',
      'image': 'assets/images/classroom/1.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': '(lǎoshī)',
      'chinese': '老师',
      'soundAsset': 'assets/sound_clips/classroom/2.m4a',
      'meaning': 'Teacher',
      'image': 'assets/images/classroom/2.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': '(xuéxí)',
      'chinese': '学习',
      'soundAsset': 'assets/sound_clips/classroom/3.m4a',
      'meaning': 'Learning',
      'image': 'assets/images/classroom/3.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(shàngkè)',
      'chinese': '上课',
      'soundAsset': 'assets/sound_clips/classroom/4.m4a',
      'meaning': 'Classes',
      'image': 'assets/images/classroom/4.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(xiàkè)',
      'chinese': '下课',
      'soundAsset': 'assets/sound_clips/classroom/5.m4a',
      'meaning': 'After class',
      'image': 'assets/images/classroom/5.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(xiūxí)',
      'chinese': '休息',
      'soundAsset': 'assets/sound_clips/classroom/6.m4a',
      'meaning': 'To rest',
      'image': 'assets/images/classroom/6.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(kànshū)',
      'chinese': '看书',
      'soundAsset': 'assets/sound_clips/classroom/7.m4a',
      'meaning': 'Read book',
      'image': 'assets/images/classroom/7.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(tīng)',
      'chinese': '听',
      'soundAsset': 'assets/sound_clips/classroom/8.m4a',
      'meaning': 'To hear',
      'image': 'assets/images/classroom/8.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(xiě)',
      'chinese': '写',
      'soundAsset': 'assets/sound_clips/classroom/9.m4a',
      'meaning': 'To write',
      'image': 'assets/images/classroom/9.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(zuòyè)',
      'chinese': '作业',
      'soundAsset': 'assets/sound_clips//classroom/ten.m4a',
      'meaning': 'Homework',
      'image': 'assets/images/classroom/10.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(jìxù)',
      'chinese': '继续',
      'soundAsset': 'assets/sound_clips/classroom/11.m4a',
      'meaning': 'To continue',
      'image': 'assets/images/classroom/11.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': '(dú)',
      'chinese': '读',
      'soundAsset': 'assets/sound_clips/classroom/12.m4a',
      'meaning': 'To read',
      'image': 'assets/images/classroom/12.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': '(cí)',
      'chinese': '词',
      'soundAsset': 'assets/sound_clips/classroom/13.m4a',
      'meaning': 'Words',
      'image': 'assets/images/classroom/13.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(ba)',
      'chinese': '吧',
      'soundAsset': 'assets/sound_clips/classroom/14.m4a',
      'meaning':
          'Used at the end of the sentence expressing suggestion or urgency',
      'image': 'assets/images/classroom/14.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(jīntiān)',
      'chinese': '今天',
      'soundAsset': 'assets/sound_clips/classroom/15.m4a',
      'meaning': 'Today',
      'image': 'assets/images/classroom/15.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(míngtiān)',
      'chinese': '明天',
      'soundAsset': 'assets/sound_clips/classroom/16.m4a',
      'meaning': 'Tomorrow',
      'image': 'assets/images/classroom/16.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(jiàn)',
      'chinese': '见',
      'soundAsset': 'assets/sound_clips/classroom/17.m4a',
      'meaning': 'To see',
      'image': 'assets/images/classroom/17.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(zuò)',
      'chinese': '做',
      'soundAsset': 'assets/sound_clips/classroom/18.m4a',
      'meaning': 'To do something',
      'image': 'assets/images/classroom/18.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(dǎkāi)',
      'chinese': '打开',
      'soundAsset': 'assets/sound_clips/classroom/19.m4a',
      'meaning': 'To open',
      'image': 'assets/images/classroom/19.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(shū)',
      'chinese': '书',
      'soundAsset': 'assets/sound_clips/classroom/20.m4a',
      'meaning': 'Books',
      'image': 'assets/images/classroom/20.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(ài)',
      'chinese': '爱',
      'soundAsset': 'assets/sound_clips/1.mp3',
      'meaning': 'Love',
      'image': 'assets/images/21.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': '(bā)',
      'chinese': '八',
      'soundAsset': 'assets/sound_clips/3.mp3',
      'meaning': 'Eight',
      'image': 'assets/images/22.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/23.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/24.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/25.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/26.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/27.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/28.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/29.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/30.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
  ];
}
