import 'dart:ui';

import 'package:chinese_learning_app/global_variables/global_colors.dart';

class DummyData {
  static final cardData = [
    {
      'word': '(ài)',
      'chinese': '爱',
      'soundAsset': 'assets/sound_clips/1.mp3',
      'meaning': 'Love',
      'image': 'assets/images/1.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': '(bā)',
      'chinese': '八',
      'soundAsset': 'assets/sound_clips/3.mp3',
      'meaning': 'Eight',
      'image': 'assets/images/2.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/3.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/4.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/5.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/6.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/7.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/8.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/9.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/10.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(ài)',
      'chinese': '爱',
      'soundAsset': 'assets/sound_clips/1.mp3',
      'meaning': 'Love',
      'image': 'assets/images/11.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': '(bā)',
      'chinese': '八',
      'soundAsset': 'assets/sound_clips/3.mp3',
      'meaning': 'Eight',
      'image': 'assets/images/12.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/13.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/14.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/15.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/16.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/17.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/18.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/19.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/20.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(ài)',
      'chinese': '爱',
      'soundAsset': 'assets/sound_clips/1.mp3',
      'meaning': 'Love',
      'image': 'assets/images/21.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': '(bā)',
      'chinese': '八',
      'soundAsset': 'assets/sound_clips/3.mp3',
      'meaning': 'Eight',
      'image': 'assets/images/22.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/23.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/24.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/25.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/26.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/27.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/28.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/29.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/30.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/31.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/32.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/33.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/34.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/35.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/36.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/37.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/38.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/39.gif',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': '(bàba)',
      'chinese': '爸爸',
      'soundAsset': 'assets/sound_clips/2.mp3',
      'meaning': 'Father',
      'image': 'assets/images/40.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
  ];
}
