import 'dart:ui';

import 'package:chinese_learning_app/global_variables/global_colors.dart';

class DummyDataHospital {
  static final cardData = [
    {
      'word': 'Nǎlǐ',
      'chinese': '哪里',
      'soundAsset': 'assets/sound_clips/hospital/1.m4a',
      'meaning': 'where',
      'image': 'assets/images/hospital/1.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Bú shūfú',
      'chinese': '不舒服',
      'soundAsset': 'assets/sound_clips/hospital/2.m4a',
      'meaning': 'uncomfortable',
      'image': 'assets/images/hospital/2.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Gāoshāo',
      'chinese': '高烧',
      'soundAsset': 'assets/sound_clips/hospital/3.m4a',
      'meaning': 'high fever',
      'image': 'assets/images/hospital/3.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Gǎnjué',
      'chinese': '感觉',
      'soundAsset': 'assets/sound_clips/hospital/4.m4a',
      'meaning': 'feel',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Zāo tòu',
      'chinese': '糟透',
      'soundAsset': 'assets/sound_clips/hospital/5.m4a',
      'meaning': 'horrible (in a bad state)',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Qíngkuàng',
      'chinese': '情况',
      'soundAsset': 'assets/sound_clips/hospital/6.m4a',
      'meaning': 'condition',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Chūxiàn',
      'chinese': '出现',
      'soundAsset': 'assets/sound_clips/hospital/7.m4a',
      'meaning': 'appear',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Duōjiǔ',
      'chinese': '多久',
      'soundAsset': 'assets/sound_clips/hospital/8.m4a',
      'meaning': 'how long',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Zuó wǎn',
      'chinese': '昨晚',
      'soundAsset': 'assets/sound_clips/hospital/9.m4a',
      'meaning': 'last night',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Kāishǐ',
      'chinese': '开始',
      'soundAsset': 'assets/sound_clips/hospital/10.m4a',
      'meaning': 'start',
      'image': 'assets/images/hospital/10.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Yǐqián',
      'chinese': '以前',
      'soundAsset': 'assets/sound_clips/hospital/11.m4a',
      'meaning': 'before',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Zánmen',
      'chinese': '咱们',
      'soundAsset': 'assets/sound_clips/hospital/12.m4a',
      'meaning': 'We (including both the speaker and the person(s) spoken to)',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Yīyuàn',
      'chinese': '医院',
      'soundAsset': 'assets/sound_clips/hospital/13.m4a',
      'meaning': 'hospital',
      'image': 'assets/images/hospital/13.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Shìshí shàng',
      'chinese': '事实上',
      'soundAsset': 'assets/sound_clips/hospital/14.m4a',
      'meaning': 'in fact/ actually',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Chéngshì',
      'chinese': '城市',
      'soundAsset': 'assets/sound_clips/hospital/15.m4a',
      'meaning': 'city',
      'image': 'assets/images/hospital/15.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Xiān',
      'chinese': '先',
      'soundAsset': 'assets/sound_clips/hospital/16.m4a',
      'meaning': 'first',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Guàhào',
      'chinese': '挂号',
      'soundAsset': 'assets/sound_clips/hospital/17.m4a',
      'meaning': 'register (at a hospital)',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Méi wèntí',
      'chinese': '没问题',
      'soundAsset': 'assets/sound_clips/hospital/18.m4a',
      'meaning': 'no problem (okay)',
      'image': 'assets/images/hospital/18.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Yīnggāi',
      'chinese': '应该',
      'soundAsset': 'assets/sound_clips/hospital/19.m4a',
      'meaning': 'should',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Zuì hǎo',
      'chinese': '最好',
      'soundAsset': 'assets/sound_clips/hospital/20.m4a',
      'meaning': 'had better',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Diàntī',
      'chinese': '电梯',
      'soundAsset': 'assets/sound_clips/hospital/21.m4a',
      'meaning': 'elevator',
      'image': 'assets/images/hospital/21.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Sān lóu',
      'chinese': '三楼',
      'soundAsset': 'assets/sound_clips/hospital/22.m4a',
      'meaning': 'third floor',
      'image': 'assets/images/hospital/22.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Zuǒ guǎi',
      'chinese': '左拐',
      'soundAsset': 'assets/sound_clips/hospital/23.m4a',
      'meaning': 'left turn',
      'image': 'assets/images/hospital/23.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Yán',
      'chinese': '沿',
      'soundAsset': 'assets/sound_clips/hospital/24.m4a',
      'meaning': 'follow/ go along',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Zǒu dào',
      'chinese': '走到',
      'soundAsset': 'assets/sound_clips/hospital/25.m4a',
      'meaning': 'corridor',
      'image': 'assets/images/hospital/25.png',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Páizi',
      'chinese': '牌子',
      'soundAsset': 'assets/sound_clips/hospital/26.m4a',
      'meaning': 'sign',
      'image': 'assets/images/hospital/26.png',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Zài nín de yòubiān',
      'chinese': '在您的右边',
      'soundAsset': 'assets/sound_clips/hospital/27.m4a',
      'meaning': 'on your right side',
      'image': 'assets/images/hospital/27.png',
      'color': GlobalColors.secondary,
      'read': false,
    },
    {
      'word': 'Nèikē',
      'chinese': '内科',
      'soundAsset': 'assets/sound_clips/hospital/28.m4a',
      'meaning': 'internal medicine or outpatient department',
      'image': '',
      'color': const Color.fromARGB(255, 96, 168, 202),
      'read': false,
    },
    {
      'word': 'Qǐngwèn',
      'chinese': '请问',
      'soundAsset': 'assets/sound_clips/hospital/29.m4a',
      'meaning': 'May I ask…..?',
      'image': '',
      'color': GlobalColors.purple,
      'read': false,
    },
    {
      'word': 'Nàme',
      'chinese': '那么',
      'soundAsset': 'assets/sound_clips/hospital/30.m4a',
      'meaning': 'then',
      'image': '',
      'color': GlobalColors.secondary,
      'read': false,
    },
  ];
}
